source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftMonkeys_Example', :exclusive => true do
    pod 'Fabric'
end

target 'SwiftMonkeys_Tests', :exclusive => true do
    pod 'FBSnapshotTestCase'
end

target 'SwiftMonkeys_ExampleUITests', :exclusive => true do
  pod 'SwiftMonkeys', :path => '../'
end
