source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftMonkeys_Example', :exclusive => true do
  pod 'SwiftMonkeys', :path => '../'
end

target 'SwiftMonkeys_Tests', :exclusive => true do
  pod 'SwiftMonkeys', :path => '../'

  pod 'FBSnapshotTestCase'
end
